import Head from 'next/head';
import Header from '../components/Header';

export default function Home() {
  return (
    <div className='bg-gray-900'>
      <Head>
        <title>LinkedIn</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/linkedin.svg' />
      </Head>
      <Header />
    </div>
  );
}
