import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>LinkedIn</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/linkedin.svg' />
      </Head>
      LinkedIn Clone
    </div>
  );
}
