import { signOut } from 'next-auth/react';
import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>LinkedIn</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/linkedin.svg' />
      </Head>
      <button
        className='text-blue-700 font-semibold rounded-full border border-blue-700 px-5 py-1.5 transition-all hover:bg-blue-200'
        onClick={signOut}
      >
        Sign out
      </button>
    </div>
  );
}
